minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@parcel/watcher'
  - sharp
  - unrs-resolver
  - "@dablulite/rn-audio-stream@https://codeload.github.com/DaBluLite/rn-audio-stream/tar.gz/1fc551041b1c1be7b6fc7ec7ea59e93f28dbfb8d"

patchedDependencies:
  react-native-track-player@4.1.2: patches/react-native-track-player@4.1.2.patch

trustPolicy: no-downgrade
